services:

  db:
    image: postgres:16-alpine
    container_name: sip_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sip_user
      POSTGRES_PASSWORD: sip_pass
      POSTGRES_DB: sip_db
    ports:
      - "5432:5432"
    volumes:
      - sip_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sip_user -d sip_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: sip_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://sip_user:sip_pass@db:5432/sip_db
      JWT_SECRET: sip_jwt_secret_2024_muy_largo_y_seguro
      PORT: 4000
      NODE_ENV: development
    ports:
      - "4000:4000"
    volumes:
      - sip_uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: sip_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  sip_pgdata:
  sip_uploads: