services:

  db:
    image: postgres:16-alpine
    container_name: sip_db
    restart: unless-stopped
    environment:
      POSTGRES_USER:     ${POSTGRES_USER:-sip_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sip_pass}
      POSTGRES_DB:       ${POSTGRES_DB:-sip_db}
      TZ:                ${TZ:-America/Santiago}
    ports:
      - "5432:5432"
    volumes:
      - sip_pgdata:/var/lib/postgresql/data
    networks:
      - sip_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sip_user} -d ${POSTGRES_DB:-sip_db}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: sip_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL:      ${DATABASE_URL:-postgresql://sip_user:sip_pass@db:5432/sip_db}
      JWT_SECRET:        ${JWT_SECRET:-sip_jwt_secret_2024_muy_largo_y_seguro}
      PORT:              ${PORT:-4000}
      NODE_ENV:          ${NODE_ENV:-development}
      TZ:                ${TZ:-America/Santiago}
      NVR_IP:            ${NVR_IP:-200.54.84.35}
      NVR_PORT:          ${NVR_PORT:-49201}
      NVR_USER:          ${NVR_USER:-admin}
      NVR_PASS:          ${NVR_PASS:-Securitas2397*}
      VAPID_PUBLIC_KEY:  ${VAPID_PUBLIC_KEY:-BE9qpl-6nS-4sHCMeUupD8PksQ4giMSSbXO9Yi8bhiJ_jsfRWZ5_C0nskn4Dc6-VC45YoE8Yoj8pqBDJ22tBgl4}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY:-32rr-ISNKqYVwp647LuhwoadTmPog6BuCnJXSgTaESM}
      VAPID_EMAIL:       ${VAPID_EMAIL:-mailto:admin@sip.cl}
    ports:
      - "4000:4000"
    volumes:
      - sip_uploads:/app/uploads
    networks:
      - sip_network

  frontend:
    build: ./frontend
    container_name: sip_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - sip_network

volumes:
  sip_pgdata:
  sip_uploads:

networks:
  sip_network:
    driver: bridge